# Generated by Django 4.2.10 on 2024-03-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20230402_2203'),
        ('comments', '0003_alter_comment_created_by_alter_comment_modified_by'),
    ]

    operations = [
    ]
