# Generated by Django 2.1.9 on 2019-09-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('charactermessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermessage',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charactermessages_charactermessage_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charactermessage',
            name='message',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='charactermessage',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charactermessages_charactermessage_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
