# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default=b'', max_length=100)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('cost', models.PositiveIntegerField()),
                ('hidden_flag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date published')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'last updated')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_header_author', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_header_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('dabble_flag', models.BooleanField(default=False)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Header')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, default=b'', max_length=100)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('attention_flag', models.BooleanField(default=False)),
                ('bgs_flag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date published')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'last updated')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_skill_author', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_skill_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='headerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='header',
            name='skills',
            field=models.ManyToManyField(through='skills.HeaderSkill', to='skills.Skill'),
        ),
    ]
