# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='hidden_flag',
            field=models.BooleanField(default=False, verbose_name=b'hidden?'),
        ),
    ]
