# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-19 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20181202_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='single_flag',
            field=models.BooleanField(default=False, help_text='\n            Indicates that you only have to buy it once\n            (like for weapon skills)\n            ', verbose_name='Single Purchase?'),
        ),
    ]
