# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-19 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_single_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='attention_flag',
        ),
    ]
