# Generated by Django 3.0.11 on 2021-03-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20190915_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerskill',
            name='capstone_flag',
            field=models.BooleanField(default=False, help_text='\n            Indicates that this is a capstone granted when\n            requirements are met.\n            (like for weapon skills)\n            ', verbose_name='Is this a capstone?'),
        ),
    ]
