# Generated by Django 3.0.11 on 2021-09-19 22:03

from django.contrib.auth.models import Group, Permission

from django.db import migrations


def add_permission_to_group(apps, schema_editor):

    staff, created = Group.objects.get_or_create(name="Staff")
    admin, created = Group.objects.get_or_create(name="Admin")
    permissions = Permission.objects.filter(codename__in=[
        'view_all_skills',
    ])
    if permissions.count() > 0:
        staff.permissions.add(permissions)
        admin.permissions.add(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_headerskill_magic_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['tag', 'name'], 'permissions': (('view_all_skills', 'View All Skills when choosing'),)},
        ),
        migrations.RunPython(add_permission_to_group),
    ]


