# Generated by Django 3.2.15 on 2022-09-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_auto_20210919_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerskill',
            name='dabble_flag',
        ),
    ]
