# Generated by Django 3.2.17 on 2023-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_remove_headerskill_dabble_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerskill',
            options={'ordering': ['cost', 'skill__name']},
        ),
    ]
