# Generated by Django 3.2.17 on 2023-06-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_alter_headerskill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['headerskill__cost', 'name'], 'permissions': (('view_all_skills', 'View All Skills when choosing'),)},
        ),
    ]
