# Generated by Django 4.2.16 on 2024-09-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_alter_header_created_by_alter_header_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='perk_flag',
            field=models.BooleanField(default=False, help_text='\n            A permanent ability that typically takes the form of a passive \n            benefit that permanently enhances a player’scapabilities.\n            ', verbose_name='This is a Perk'),
        ),
    ]
