# Generated by Django 4.2.16 on 2024-10-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_skill_perk_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bgs_flag',
            field=models.BooleanField(default=False, help_text='\n            An ability that is typically used between events instead of during them.\n            ', verbose_name='Between Game Ability'),
        ),
    ]
