# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '__first__'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_character_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='headers',
            field=models.ManyToManyField(to='skills.Header'),
        ),
        migrations.AddField(
            model_name='character',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='character',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_character_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterskills',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AddField(
            model_name='characterskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='characterlog',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AddField(
            model_name='characterlog',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_characterlog_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='characters.CharacterSkills', to='skills.Skill'),
        ),
    ]
