# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20170530_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'SkillGrant', b'Skill Grant'), (b'HeaderGrant', b'Header Grant')], default=b'SkillGrant', max_length=20)),
                ('correlated_id', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('free', models.BooleanField(default=False)),
                ('picks_remaining', models.PositiveIntegerField(default=10000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
    ]
