# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '__first__'),
        ('characters', '0003_charactergrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='origins',
            field=models.ManyToManyField(to='origins.Origin'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[(b'alive', b'Alive'), (b'dead', b'Dead'), (b'retired', b'Retired')], default=b'alive', max_length=50),
        ),
    ]
