# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-22 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20180623_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
    ]
