# Generated by Django 2.1.9 on 2019-09-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20190321_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_character_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_character_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Dead'), ('retired', 'Retired')], default='alive', max_length=50),
        ),
        migrations.AlterField(
            model_name='charactergrant',
            name='type',
            field=models.CharField(choices=[('SkillGrant', 'Skill Grant'), ('HeaderGrant', 'Header Grant')], default='SkillGrant', max_length=20),
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_characterlog_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
