# Generated by Django 3.0.11 on 2021-08-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20210811_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cp_available',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
