# Generated by Django 3.0.11 on 2022-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20210811_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pronouns',
            field=models.CharField(default='', max_length=25, verbose_name='character_pronouns'),
        ),
    ]
