# Generated by Django 3.0.11 on 2022-01-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pronouns',
            field=models.CharField(default='', max_length=25, verbose_name='pronouns'),
        ),
    ]
