# Generated by Django 3.2.11 on 2022-02-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20220109_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskills',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
