# Generated by Django 3.2.11 on 2022-02-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_auto_20210919_1803'),
        ('characters', '0011_alter_characterskills_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='characters.CharacterSkills', to='skills.HeaderSkill'),
        ),
        migrations.AlterField(
            model_name='characterskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.headerskill'),
        ),
    ]
