# Generated by Django 3.2.13 on 2022-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_auto_20220206_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
