# Generated by Django 3.2.15 on 2022-08-17 22:58

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0004_auto_20220227_0936'),
        ('skills', '0009_auto_20210919_1803'),
        ('characters', '0013_alter_character_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='headers',
            field=models.ManyToManyField(null=True, to='skills.Header'),
        ),
        migrations.AlterField(
            model_name='character',
            name='history',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='origins',
            field=models.ManyToManyField(null=True, to='origins.Origin'),
        ),
    ]
