# Generated by Django 3.2.15 on 2022-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20220817_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cp_initial',
            field=models.PositiveIntegerField(default=25, help_text='Record of initial points in case a character has to be rebuilt.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='cp_available',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
