# Generated by Django 3.2.15 on 2022-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0004_auto_20220227_0936'),
        ('skills', '0010_remove_headerskill_dabble_flag'),
        ('characters', '0015_auto_20220821_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='headers',
            field=models.ManyToManyField(to='skills.Header'),
        ),
        migrations.AlterField(
            model_name='character',
            name='origins',
            field=models.ManyToManyField(to='origins.Origin'),
        ),
    ]
