# Generated by Django 3.2.15 on 2022-09-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_auto_20220911_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='history_approved_flag',
            field=models.BooleanField(default=False, verbose_name='History Approved'),
        ),
        migrations.AlterField(
            model_name='character',
            name='active_flag',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
