# Generated by Django 3.2.15 on 2022-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20220911_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='concept_approved_flag',
            field=models.BooleanField(default=False, verbose_name='Concept Approved'),
        ),
    ]
