# Generated by Django 3.2.15 on 2022-12-18 23:32

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_character_concept_approved_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='concept',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
