# Generated by Django 3.2.17 on 2023-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_character_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cp_available',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='cp_initial',
            field=models.PositiveIntegerField(default=30, help_text='Record of initial points in case a character has to be rebuilt.'),
        ),
    ]
