# Generated by Django 3.2.17 on 2023-06-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_auto_20230406_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
    ]
