# Generated by Django 3.2.17 on 2023-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_alter_character_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'permissions': (('reset_points', 'Can reset points'),)},
        ),
    ]
