# Generated by Django 3.2.17 on 2023-09-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20230924_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'permissions': (('reset_points', 'Can reset points'), ('update_influence', 'Can update influence'))},
        ),
    ]
