# Generated by Django 4.2.10 on 2024-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_alter_character_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='reset_occurred_flag',
            field=models.BooleanField(default=False, verbose_name='Has been reset'),
        ),
    ]
