# Generated by Django 4.2.16 on 2024-10-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_character_reset_occurred_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='reset_occurred_flag',
            field=models.BooleanField(default=False, help_text="The skills for this character have already been reset, and can't be again.", verbose_name='Skills have been reset'),
        ),
    ]
