# Generated by Django 4.2.16 on 2024-10-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_alter_character_reset_occurred_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterlog',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
    ]
