# Generated by Django 4.2.16 on 2024-10-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_alter_characterlog_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterLog',
        ),
    ]
