# Generated by Django 4.2.16 on 2025-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_delete_characterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='influence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'permissions': (('update_influence', 'Can update influence'), )},
        ),
    ]
