# Generated by Django 4.2.16 on 2026-09-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_alter_event_options'),
        ('characters', '0032_add_influence_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorruptionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('threshold', models.PositiveIntegerField(help_text='Lowest end of game influence, inclusive, that reaches this level.')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-threshold'],
            },
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'permissions': (('reset_points', 'Can reset points'), ('update_influence', 'Can update influence'))},
        ),
        migrations.CreateModel(
            name='CharacterEventInfluence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence_input', models.PositiveIntegerField(blank=True, null=True, verbose_name='Influence Input')),
                ('start_influence', models.PositiveIntegerField(blank=True, null=True, verbose_name='Start of Game Influence')),
                ('end_influence', models.PositiveIntegerField(blank=True, null=True, verbose_name='End of Game Influence')),
                ('corruption_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influence_rows', to='characters.character')),
                ('corruption_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.corruptionlevel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influence_rows', to='events.event')),
                ('processed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_influence_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event__event_date', 'character__name'],
                'unique_together': {('event', 'character')},
            },
        ),
    ]
