# Generated by Django 2.1.9 on 2019-09-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betweengameskills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betweengameskill',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.Player'),
        ),
    ]
