# Generated by Django 3.2.12 on 2022-04-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_auto_20220410_1046'),
        ('betweengameskills', '0002_auto_20190915_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betweengameskill',
            name='answer_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='answered'),
        ),
        migrations.AlterField(
            model_name='betweengameskill',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'user__is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player'),
        ),
    ]
