# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgs_p',
            field=models.BooleanField(default=True, verbose_name='Allow Between Game Skills'),
        ),
        migrations.AlterField(
            model_name='event',
            name='oog_p',
            field=models.BooleanField(default=False, verbose_name='Out of game event'),
        ),
    ]
