# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170530_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='For reference, such as "Spring 2, 2010"', max_length=255),
        ),
    ]
