# Generated by Django 2.1.9 on 2019-09-15 13:19

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180317_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For reference, such as "Season Pass"', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventregistrationitem',
            name='events',
            field=models.ManyToManyField(related_name='events', to='events.Event'),
        ),
    ]
