# Generated by Django 2.1.9 on 2019-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190915_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationitem',
            name='order',
            field=models.IntegerField(default=0, help_text='What order should this appear on the page?'),
        ),
    ]
