# Generated by Django 2.1.9 on 2019-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventregistrationitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationitem',
            name='available',
            field=models.BooleanField(default=True, help_text='Is this still available?'),
        ),
    ]
