# Generated by Django 2.1.9 on 2019-10-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistrationitem_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistrationitem',
            options={'ordering': ['order']},
        ),
    ]
