# Generated by Django 3.2.12 on 2022-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191020_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgs_due_date',
            field=models.DateField(default='03/27/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default='03/27/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pel_due_date',
            field=models.DateField(default='03/27/2022'),
        ),
    ]
