# Generated by Django 4.2.16 on 2026-09-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'permissions': (('cast_registration', 'Can register as a cast member.'),)},
        ),
    ]
