# Generated by Django 3.2.15 on 2022-11-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20220817_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgs_due_date',
            field=models.DateField(default='11/20/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default='11/20/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pel_due_date',
            field=models.DateField(default='11/20/2022'),
        ),
    ]
