# Generated by Django 3.2.15 on 2022-12-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20221120_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgs_due_date',
            field=models.DateField(default='12/08/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default='12/08/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pel_due_date',
            field=models.DateField(default='12/08/2022'),
        ),
    ]
