# Generated by Django 3.2.15 on 2022-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20221216_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgs_due_date',
            field=models.DateField(default='12/17/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default='12/17/2022'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pel_due_date',
            field=models.DateField(default='12/17/2022'),
        ),
    ]
