# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('type', models.CharField(choices=[(b'race', b'Race'), (b'background', b'Background')], default=b'race', max_length=15, verbose_name='Type')),
                ('hidden_flag', models.BooleanField(default=False, verbose_name='Hidden?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date published')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'last updated')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origins_origin_author', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origins_origin_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OriginSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origins.Origin')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='origin',
            name='skills',
            field=models.ManyToManyField(through='origins.OriginSkill', to='skills.Skill'),
        ),
    ]
