# Generated by Django 3.0.11 on 2021-07-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0002_auto_20190915_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='type',
            field=models.CharField(choices=[('people', 'People'), ('tradition', 'Tradition')], default='people', max_length=15, verbose_name='Type'),
        ),
    ]
