# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('skills', '0002_auto_20181202_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('object_id', models.PositiveIntegerField()),
                ('new_cost', models.PositiveIntegerField(default=0)),
                ('free', models.BooleanField(default=False, help_text='This is granted for free if the requirements are met.')),
                ('picks_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
    ]
