# Generated by Django 2.2.12 on 2020-06-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0002_auto_20190915_0919'),
        ('skills', '0005_auto_20190915_0919'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules', '0002_auto_20190915_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('number_of_purchases', models.PositiveIntegerField(help_text='How many you much purchase to me the requirement')),
                ('points', models.PositiveIntegerField(help_text='how many character points')),
                ('number_of_different_skills', models.PositiveIntegerField(help_text='how many different skills must be purchased')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'origins'), ('model', 'Origin')), models.Q(('app_label', 'skills'), ('model', 'Header')), models.Q(('app_label', 'skills'), ('model', 'Skill')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('header', models.ForeignKey(help_text='What header the skills must be in.', on_delete=django.db.models.deletion.CASCADE, to='skills.Header')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origins.Origin')),
                ('skill', models.ForeignKey(help_text='What skill must be purchased', on_delete=django.db.models.deletion.CASCADE, to='skills.Skill')),
            ],
        ),
    ]
