# Generated by Django 2.2.12 on 2020-06-28 20:22

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20200628_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='free',
            field=models.BooleanField(blank=True, default=False, help_text='This is granted for free if the requirements are met.'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='new_cost',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
