# Generated by Django 3.0.11 on 2021-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_auto_20200628_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='skill',
        ),
    ]
