# Generated by Django 3.0.11 on 2021-05-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_headerskill_capstone_flag'),
        ('rules', '0008_remove_rule_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.HeaderSkill'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='number_of_purchases',
            field=models.PositiveIntegerField(blank=True, help_text='How many you must purchase to meet the requirement', null=True),
        ),
    ]
