# Generated by Django 3.0.11 on 2021-06-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_header_open_flag'),
        ('rules', '0009_auto_20210508_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='additional_header',
            field=models.ForeignKey(blank=True, help_text='Additional header before you can purchase this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_headers', to='skills.Header'),
        ),
    ]
