# Generated by Django 3.2.15 on 2022-11-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_rule_universal_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='universal_flag',
            field=models.BooleanField(default=False, help_text='All characters get this.', verbose_name='Universal'),
        ),
    ]
