# Generated by Django 3.2.17 on 2023-10-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_alter_skill_options'),
        ('betweengameabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betweengameability',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.headerskill'),
        ),
    ]
