# Generated by Django 3.2.23 on 2024-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betweengameabilities', '0004_alter_betweengameability_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='betweengameability',
            name='non_ability_source_flag',
            field=models.BooleanField(default=False, help_text='Choose this for abilities granted by potions or other, non-ability sources.', verbose_name='Other'),
        ),
    ]
