# Generated by Django 3.2.23 on 2024-01-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_alter_skill_options'),
        ('betweengameabilities', '0005_betweengameability_non_ability_source_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betweengameability',
            name='ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.headerskill'),
        ),
    ]
