# Generated by Django 4.2.10 on 2024-02-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0037_alter_registration_registration_request'),
        ('betweengameabilities', '0006_alter_betweengameability_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betweengameability',
            name='count',
            field=models.PositiveIntegerField(help_text='If you enter 0, please include a description of where you are getting the ability from.'),
        ),
        migrations.AlterField(
            model_name='betweengameability',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_author', to='players.player'),
        ),
        migrations.AlterField(
            model_name='betweengameability',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updater', to='players.player'),
        ),
    ]
