# Generated by Django 4.2.10 on 2024-03-20 00:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('betweengameabilities', '0007_alter_betweengameability_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betweengameability',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
