# Generated by Django 4.2.16 on 2024-10-05 01:04

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import talesofvalor.players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_alter_pel_options_remove_pel_player_pel_character_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
        ('betweengameabilities', '0008_betweengameability_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betweengameability',
            options={'ordering': ('-event', 'character__name'), 'verbose_name': 'Between Game Ability', 'verbose_name_plural': 'Between Game Abilities'},
        ),
        migrations.AlterField(
            model_name='betweengameability',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to=talesofvalor.players.models.limit_to_staff, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player'),
        ),
        migrations.AlterField(
            model_name='betweengameability',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
