# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170530_2045'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('likes', models.TextField(blank=True, default=b'')),
                ('dislikes', models.TextField(blank=True, default=b'')),
                ('best_moments', models.TextField(blank=True, default=b'')),
                ('worst_moments', models.TextField(blank=True, default=b'')),
                ('learned', models.TextField(blank=True, default=b'')),
                ('data', djangocms_text_ckeditor.fields.HTMLField(blank=True, default=b'')),
                ('rating', models.PositiveIntegerField(choices=[(5, b'Amazing'), (4, b'Good'), (3, b'Average'), (2, b'Fair'), (1, b'Poor')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
