# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_registration'),
    ]

    operations = [
    ]
