# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20170730_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'permissions': (('change_any_player', 'Can change any player'), ('view_any_player', 'Can view any player'))},
        ),
    ]
