# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20180317_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mealplan_flag',
            field=models.BooleanField(default=False, help_text='Has the player signed up for a meal plan?'),
        ),
    ]
