# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20180623_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='staff_attention_flag',
            field=models.BooleanField(default=False),
        ),
    ]
