# Generated by Django 2.1.9 on 2020-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20191022_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='paypal_order_id',
            field=models.TextField(blank=True, default='', help_text='Order recieved from PayPal system.'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='status',
            field=models.TextField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('complete', 'Complete'), ('refused', 'Refused')], default='requested', help_text='Status of the request in ToV system.'),
        ),
    ]
