# Generated by Django 2.1.9 on 2020-02-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20200210_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='car_registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.RegistrationRequest'),
        ),
    ]
