# Generated by Django 3.0.11 on 2021-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20200420_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pel',
            name='rating',
            field=models.PositiveIntegerField(choices=[(5, 'Amazing'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor')], null=True),
        ),
    ]
