# Generated by Django 3.0.11 on 2022-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20210718_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_pronouns',
            field=models.CharField(default='', max_length=64),
        ),
    ]
