# Generated by Django 3.0.11 on 2022-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_player_player_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='pel',
            name='heavy_armor_worn_flag',
            field=models.BooleanField(default=False, help_text='This character wore heavy armor the entire event.', verbose_name='Character wore heavy armor this event?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_pronouns',
            field=models.CharField(default='', max_length=25),
        ),
    ]
