# Generated by Django 3.0.11 on 2022-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_player_player_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pronouns',
            field=models.CharField(default='', max_length=25),
        ),
    ]
