# Generated by Django 3.0.11 on 2022-01-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_auto_20220109_1450'),
        ('players', '0019_auto_20220109_1504'),
    ]

    operations = [
    ]
