# Generated by Django 3.2.11 on 2022-02-06 22:30

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_merge_20220109_1558'),
    ]

    operations = [
    ]
