# Generated by Django 3.2.11 on 2022-02-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_auto_20220124_1753'),
        ('players', '0023_pelfilterbyeventmodel'),
    ]

    operations = [
    ]
