# Generated by Django 3.2.11 on 2022-02-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_auto_20220206_1730'),
        ('players', '0024_merge_20220207_1722'),
    ]

    operations = [
    ]
