# Generated by Django 3.2.12 on 2022-03-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_merge_20220207_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PELFilterByEventModel',
        ),
    ]
