# Generated by Django 3.2.12 on 2022-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_delete_pelfilterbyeventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PELFilterByEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_selector', models.CharField(choices=[('Spring 1, 2019', 'Spring 1 2019 - 05-01-2019'), ('Spring 2, 2019', 'Spring 2 2019 - 06-02-2019'), ('Fall 1, 2019', 'Fall 1 2019 - 09-03-2019'), ('Fall 2, 2019', 'Fall 2 2019 - 10-04-2019'), ('Spring 1, 2020', 'Spring 1 2020 - 05-08-2020')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='food_allergies',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='food_allergies',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
