# Generated by Django 3.2.11 on 2022-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_auto_20220327_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PELFilterByEventModel',
        ),
        migrations.AddField(
            model_name='player',
            name='food_allergies',
            field=models.TextField(default=''),
        ),
    ]
