# Generated by Django 3.2.15 on 2022-08-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_auto_20220410_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vegan_flag',
            field=models.BooleanField(default=False, help_text='Vegan meal request.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='vegetarian_flag',
            field=models.BooleanField(default=False, help_text='Vegetarian meal request.'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='vegan_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='vegetarian_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='food_allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vehicle_registration',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='vehicle_registration',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='License Plate'),
        ),
    ]
