# Generated by Django 3.2.15 on 2022-11-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_auto_20220817_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='no_car_flag',
            field=models.BooleanField(default=False, verbose_name='No car on site.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='site_transportation',
            field=models.TextField(blank=True, default='', help_text='The person or method you got to site with:  Uber, player name.  In case of emergencies.', verbose_name='Came to site with/by'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='no_car_flag',
            field=models.BooleanField(default=False, verbose_name='No car on site.'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='site_transportation',
            field=models.TextField(blank=True, default='', help_text='The person or method you got to site with:  Uber, player name.  In case of emergencies.', verbose_name='Came to site with/by'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vegan_flag',
            field=models.BooleanField(default=False, verbose_name='Vegan Meal Requested'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vegetarian_flag',
            field=models.BooleanField(default=False, verbose_name='Vegetarian Meal Requested'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='vegan_flag',
            field=models.BooleanField(default=False, verbose_name='Vegan Meal Requested'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='vegetarian_flag',
            field=models.BooleanField(default=False, verbose_name='Vegetarian Meal Requested'),
        ),
    ]
