# Generated by Django 3.2.15 on 2022-12-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_auto_20221120_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pay_at_door_flag',
            field=models.BooleanField(default=False, verbose_name='Payment brought to game'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='already_paid_flag',
            field=models.BooleanField(default=False, verbose_name='Paid by another method.'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='pay_at_door_flag',
            field=models.BooleanField(default=False, verbose_name='Payment brought to game'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='site_transportation',
            field=models.TextField(blank=True, default='', help_text='The person or method you got to site with:  Uber, player name.  In case of emergencies.', verbose_name='Alternative Transportation'),
        ),
    ]
