# Generated by Django 3.2.15 on 2022-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_auto_20221208_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='already_paid_flag',
            field=models.BooleanField(default=False, verbose_name='Paid by another method.'),
        ),
    ]
