# Generated by Django 3.2.17 on 2023-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_registration_already_paid_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pronouns',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
