# Generated by Django 3.2.17 on 2023-07-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_auto_20230608_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
    ]
