# Generated by Django 3.2.17 on 2023-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_alter_registration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': (('register_as_cast', 'Can register as cast'),)},
        ),
    ]
