# Generated by Django 3.2.17 on 2023-07-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_alter_registration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.registrationrequest'),
        ),
    ]
