# Generated by Django 2.1.9 on 2019-09-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190317_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.Character'),
        ),
    ]
